version: "3"
services:
  client:
    container_name: "ui"
    build: ./ui
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - webapp
  api:
    container_name: "api"
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - webapp
networks:
  webapp: